apiVersion: v1
kind: ConfigMap
metadata:
  name: semarket-config
  namespace: semarketplace
data:
  PORT: "8080"
  VITE_API_URL: "/api"
  VITE_USE_MOCK: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: semarket-secret
  namespace: semarketplace
type: Opaque
stringData:
  POSTGRES_USER: "semarket"
  POSTGRES_PASSWORD: "semarket_k8s_secure_pass_2026"
  POSTGRES_DB: "semarketplace"
  JWT_SECRET: "semarketplace_super_secret_jwt_key_k8s_enterprise_2026"
  DATABASE_URL: "postgres://semarket:semarket_k8s_secure_pass_2026@postgres-service:5432/semarketplace?sslmode=disable"
